### ISSUE TITLE
New MISC samples

### ISSUE THREAD

**Issue by Sti2nd** [LMMS/assets#12]
Updated
- Cabasa/shaker/maracas. What is the difference? I don't think all of these are needed when looking at all the samples and .ds files which already is white noise, but one shaker and/or maracas in high quality is good. 
  http://www.freesound.org/people/menegass/packs/5824/
  http://www.freesound.org/people/dfeltch/sounds/171685/
  http://emmanuelprot.free.fr/Drums%20kit%20Manu/Vibraslap.wav
- Already is a snape sound in LMMS, no need for another one?
- Tambourine (not CC0, must ask): http://www.freesound.org/people/ahjteam/sounds/210639/

**Comment by WrillicR** [comment]
This issue is outdated by the current scope of the project. Also most sounds come from freesound.org, which is a great source of free samples, but generally not one we can reliably take from for this project without a guarantee from the freesound contributer that the samples are self-made and CC0. Closing this.
